pipeline:

  build_docker_image:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t image .

  latest_image_to_quay:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_cassandra_backup" -p=${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/cassandra-backup-to-s3:latest
      - docker tag image quay.io/ukhomeofficedigital/cassandra-backup-to-s3:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/cassandra-backup-to-s3:latest
      - docker push quay.io/ukhomeofficedigital/cassandra-backup-to-s3:${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  tag_image_to_quay:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_cassandra_backup" -p=${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/cassandra-backup-to-s3:${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/cassandra-backup-to-s3:${DRONE_TAG}
    when:
      event: tag

services:
  dind:
    image: docker:1.12-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
