#!/usr/bin/env bash

set -e

TIME=`date "+%Y%m%d_%H%M"`
FILENAME=${CASSANDRA_BACKUPS:-${CASSANDRA_DATA}}/${KUBERNETES_POD_NAME}_${CASSANDRA_KEYSPACE}_${TIME}.tar.gz

echo "-- Creating new snapshot for ${CASSANDRA_KEYSPACE} called ${TIME} --"
nodetool -h ${CASSANDRA_HOST} -p ${CASSANDRA_PORT} snapshot ${CASSANDRA_KEYSPACE} -t ${TIME}

echo "-- Archiving snapshots... --"

dirs=$(find ${CASSANDRA_DATA}/${CASSANDRA_KEYSPACE} -name ${TIME})
tar -cvzf ${FILENAME} $dirs

if [[ -z ${CASSANDRA_BACKUPS} ]]; then
  echo "-- Pushing snapshots to S3... --"

  aws s3 mv ${FILENAME} s3://${AWS_BUCKET_NAME} \
          --sse-kms-key-id ${AWS_KMS_ID} \
          --sse aws:kms

  echo "-- S3 backup complete! --"
else
  echo "-- Backup created @ ${FILENAME} --"

  echo "--- Removing old archives... --"
  find ${CASSANDRA_BACKUPS}/* -mtime +${RETAIN_DAYS} -exec rm {} \;
fi

echo "-- Clearing old snapshots --"
nodetool -h ${CASSANDRA_HOST} -p ${CASSANDRA_PORT} clearsnapshot
echo "-- Backup complete --"
